### ISSUE TITLE
Include 3MF versions?

### ISSUE THREAD

**Issue by pencerw** [kickstarter/kickstarter-autodesk-3d#1]
3MF is lightweight, portable, and a heck of a lot better than STL ;) @andreasbastian, let me know if I can help generating the files (if you're open to including them)!

**Comment by andreasbastian** [comment]
That's a great idea!  I haven't worked with 3MF much, want to maybe create a 3MF version of the geometry and then submit a pull request?  I assume 3MF is most useful when you convert from a STEP or other more data-rich format than STL, is the f3d file a reasonable place to start or should I send you a STEP/IGES?

**Comment by pencerw** [comment]
@andreasbastian yeah, starting from CAD would make the most sense. Want to attach one here?

**Comment by pencerw** [comment]
@andreasbastian thanks! So, a question. 3MF has a concept of "objects," described [here](https://github.com/3MFConsortium/spec_core/blob/master/3MF%20Core%20Specification.md#chapter-4-object-resources). Since this is a multi-body part, there are a few ways we can describe it:
* As a 6-object part, each of which contains a single-shelled mesh
* As a single object part, which contains a 6-shelled mesh

(We could also be fancy and use ["components"](https://github.com/3MFConsortium/spec_core/blob/master/3MF%20Core%20Specification.md#42-components), in which case we would have a 2-object part, one of which is a component which is repeated 5 times with transforms. This would be slick but maybe a little too clever for the intended use.)

I'm attaching screenshots from Element - see the object browser for a sense of how this works. Which do you think is more appropriate for the application? The actual 3MF files (which you can also open in Element, Meshmixer, Netfabb, etc) are attached as well.


![1 multi shelled object](https://user-images.githubusercontent.com/3917864/45416936-eb9bff00-b678-11e8-8917-05055117e003.png)
![6 objects](https://user-images.githubusercontent.com/3917864/45416937-eb9bff00-b678-11e8-8eb6-e446bca28577.png)
[3mf options.zip](https://github.com/kickstarter/kickstarter-autodesk-3d/files/2374560/3mf.options.zip)

**Comment by andreasbastian** [comment]
Nice, I think that the single object 3mf version will be best here to ensure that the cylindrical pins always stay in the exact same positions relative to the main body.  Had I modeled this so that the holes that the pins reside in change diameter, using the component trick would have been slick, but I change the pin diameters, so each has to stay in its respective hole. 

Is there anything else that you'd like to change in the "one object.3mf" file or should I rename it "ksr_fdmtest_v4.3mf" and add it to the FDM protocol folder?  Thanks again for making the file!

**Comment by pencerw** [comment]
Ah ah! Sorry I didn't notice the differing sizes. 

I'll make the PR in just a minute!
