### ISSUE TITLE
What are the "Standart" settings?

### ISSUE THREAD

**Issue by X3msnake** [kickstarter/kickstarter-autodesk-3d#10]
You should disclaim, or better have a config json of this so called standart!

**Comment by andreasbastian** [comment]
Great question!  Standard settings are the settings that a printer/slicer/materials manufacturer/provider prescribe for using their product.  I find this is a good way to evaluate how well "tuned" a shipping system (hardware, software, plus materials) actually is.   That being said, individual parts of a system can be further probed by deviating from "standard" or default settings and a subset of parameters from another system.  

For the scope of this project, I'm sticking to default settings, though I'd encourage you to check out the [2015 Make Magazine 3D printer Shootout models](https://www.thingiverse.com/thing:533472), which are great for doing more specific comparisons between machines/materials/slicers/electronics and associated parameters.

**Comment by X3msnake** [comment]
thanks for the clarification Master
