### ISSUE TITLE
Bad method of calculating dimensional accuracy

### ISSUE THREAD

**Issue by drzejkopf** [kickstarter/kickstarter-autodesk-3d#6]
In presented example, X error and Y error values are presented as positive or negative values, while they should be presented as absolute values. For example, let's assume we've got following X measurements: 26mm, 19mm, 15mm, 9.5mm, 4.5mm, then, using current method X Error (X Error=Measuerd X - Target) will be: 1mm, -1mm, 0mm, -0.5mm, 0.5mm, and then average error will be 0, while real error is huge. Method should be changed to use absolute values as X Error and Y Error values (X,Y Error=abs(Measured X,Y - Target)

**Comment by andreasbastian** [comment]
Great catch, this is definitely incorrect!  Just pushed an update to the FDM protocol fixing this.
